export const treeNodes = [
  {
    _id: "AJuLXkPwTp5dAYibR",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: null,
    type: "factory",
    name: "Company",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1574083851047,
    spotId: "CGjivWHgGeAHkFtzG",
  },
  {
    _id: "eDQmdP2nTwgHoxBuS",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: null,
    type: "factory",
    name: "Klanten Tests",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1574170057476,
    spotId: "vQph6nKXFzNzAuJpY",
  },
  {
    _id: "ak7crSpNP56ZD4nFs",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "AJuLXkPwTp5dAYibR",
    type: "zone",
    name: "Web",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1575378301772,
    spotId: "3y7tFHgKgTNctheL2",
  },
  {
    _id: "meo8L4sPQYd6NbM4g",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "ak7crSpNP56ZD4nFs",
    type: "workinstruction",
    name: "App Usability Checklist",
    workinstructionId: "soFaE3m6fCfq6KxrD",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1575378313313,
  },
  {
    _id: "iivGuAKQnbEtaG2qH",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "ak7crSpNP56ZD4nFs",
    type: "zone",
    name: "Tutorials",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1578297648091,
    spotId: "w2MdBq79EEuEuTgei",
  },
  {
    _id: "GeAQ4ssegbS36D2Pg",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Work instructions",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1578297809156,
    spotId: "YNgRnhj3nCQufuSoC",
  },
  {
    _id: "5EazMooSjuoSEgCgE",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Management",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1578300985025,
    spotId: "khorYdTFfxBt9ccnA",
  },
  {
    _id: "7rnxeqMmLo8podGxS",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5EazMooSjuoSEgCgE",
    type: "workinstruction",
    name: "?⃝ User Management - simple",
    createdBy: "74ZkWEMFCWQCLLXKX",
    createdOn: 1578301026177,
    workinstructionId: "Wbv2wYfjXecH7z6Dm",
  },
  {
    _id: "aeCf38994BTaqxArL",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KQaLPx75ZBZgq92Bb",
    type: "workinstruction",
    name: "?⃝ Link Sharing",
    createdBy: "6e5xmYydZNz6mzyv9",
    createdOn: 1581428290951,
    workinstructionId: "yvtwFsdoTxRcsLu4r",
  },
  {
    _id: "d4weK9k9NdpnaX25L",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KQaLPx75ZBZgq92Bb",
    type: "workinstruction",
    name: "?⃝ Create work instruction - simple",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583832454697,
    workinstructionId: "Wkges7knhDxiWaC9o",
  },
  {
    _id: "jahSartgBjHqSvmLk",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KQaLPx75ZBZgq92Bb",
    type: "workinstruction",
    name: "?⃝ Create work instruction - advanced",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583832502880,
    workinstructionId: "MPKxazBBnBC3TbR7g",
  },
  {
    _id: "qapoZFWQdw87CnyRw",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KQaLPx75ZBZgq92Bb",
    type: "workinstruction",
    name: "?⃝ Changing the flow of a workstation",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583846911823,
    workinstructionId: "aPrWSuqWroXmauBPM",
  },
  {
    _id: "wDZJQF6qRiX6yTDJo",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Products",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583847725653,
    spotId: "LMTPrEbB8udR2t87o",
  },
  {
    _id: "thZfxac8bNBq29sQe",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Collections",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583847736716,
    spotId: "yuN5TBnJcSfpxzfK5",
  },
  {
    _id: "Ah5fqceG2fjFBGyL8",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Improvement boards",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583848503114,
    spotId: "cabPD7W5ozGhdJwys",
  },
  {
    _id: "BLBCZh5rz4ayBDJmk",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Ah5fqceG2fjFBGyL8",
    type: "workinstruction",
    name: "?⃝Working with Improvement Boards",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583849363855,
    workinstructionId: "T8veQLsEtaaHwAesY",
  },
  {
    _id: "ehNriWCuWcHen8teE",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "wDZJQF6qRiX6yTDJo",
    type: "workinstruction",
    name: "?⃝ Working with products - simple",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583932982939,
    workinstructionId: "otawJbLNaHAiZtdjh",
  },
  {
    _id: "3aXBqab5zhBDzTY6A",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "wDZJQF6qRiX6yTDJo",
    type: "workinstruction",
    name: "?⃝ Docx reports",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1583934410003,
    workinstructionId: "QdxvFioxLdckoLNbd",
  },
  {
    _id: "DfvLpaeHAb8PxuLDG",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5EazMooSjuoSEgCgE",
    type: "workinstruction",
    name: "?⃝ User Management - advanced",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1584367681231,
    workinstructionId: "oE9QzEqb3H5WjS6XF",
  },
  {
    _id: "u3c4ZD7dGx6GD4kGN",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "thZfxac8bNBq29sQe",
    type: "workinstruction",
    name: "?⃝ Resources",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1595595159113,
    workinstructionId: "DhkhJtDNm2TD2pgQj",
  },
  {
    _id: "gyKCKWjKkfJKcJMDE",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "thZfxac8bNBq29sQe",
    type: "workinstruction",
    name: "?⃝ Variants",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1595595499471,
    workinstructionId: "BfojTCRNcexFvukxJ",
  },
  {
    _id: "aWd2QttkGSdnDtoQJ",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "eDQmdP2nTwgHoxBuS",
    type: "zone",
    name: "Video",
    createdBy: "6e5xmYydZNz6mzyv9",
    createdOn: 1597150476379,
    spotId: "2WD3F38e6JwPu8c24",
  },
  {
    _id: "HdMXButd6bgom4Y57",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "aWd2QttkGSdnDtoQJ",
    type: "workinstruction",
    name: "Video",
    createdBy: "6e5xmYydZNz6mzyv9",
    createdOn: 1597150484100,
    workinstructionId: "iZDYXkZxpgbcxBfDy",
  },
  {
    _id: "2KaqTGquhYDgycpTD",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Time Study",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1597398306892,
    spotId: "waLRZ4mPENJi3MWjg",
  },
  {
    _id: "YfNMcW6oLEimaQPAr",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "2KaqTGquhYDgycpTD",
    type: "workinstruction",
    name: "?⃝ Time Study - simple",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1597398328539,
    workinstructionId: "spSqvrA77hkhed7AR",
  },
  {
    _id: "HDaDnzfGMW2HNdm4v",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "wDZJQF6qRiX6yTDJo",
    type: "workinstruction",
    name: "?⃝ Parameters",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1597828502767,
    workinstructionId: "hvoqr8Nz6Pu8LSBW6",
  },
  {
    _id: "2gEiKaG6NHRiDc3J6",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "thZfxac8bNBq29sQe",
    type: "workinstruction",
    name: "?⃝ Recordings",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1598011297195,
    workinstructionId: "EQHvtnzHhNQ7rfxZf",
  },
  {
    _id: "hbDNTvZiNkTBgmCZe",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "workinstruction",
    name: "Not in use",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1600263310074,
    workinstructionId: "A4jHwDFqc5bhFFD4W",
  },
  {
    _id: "cxXikphpt9jYZkfR5",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Explore",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1601364326450,
    spotId: "vbhRWfM32uboHdEqs",
  },
  {
    _id: "9r9cqSFCouLqBBj4o",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "cxXikphpt9jYZkfR5",
    type: "workinstruction",
    name: "How to define an article and factory structure in Company",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1601364488048,
    workinstructionId: "9wt27X55tng4RhNKz",
  },
  {
    _id: "MuXzhwdwMyTGhy6R8",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "cxXikphpt9jYZkfR5",
    type: "workinstruction",
    name: "Articles",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1601449765384,
    workinstructionId: "fmM38DdwoAF582azz",
  },
  {
    _id: "KrNYLPGmMFG8Jo9LP",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "cxXikphpt9jYZkfR5",
    type: "workinstruction",
    name: "Factory",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1601449807682,
    workinstructionId: "gXRmZxRquQXzpEBXz",
  },
  {
    _id: "5TaSpTDTznYzWrh58",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Welcome to Company",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1601555894144,
    spotId: "NkBbc45SAFYruv58X",
  },
  {
    _id: "2hk7L95hRmCTcvaED",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5TaSpTDTznYzWrh58",
    type: "workinstruction",
    name: "Introduction to Company",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1601555949929,
    workinstructionId: "4cmhereArg3PnohNS",
  },
  {
    _id: "bLJmZLQ4C9STAoGi4",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5TaSpTDTznYzWrh58",
    type: "workinstruction",
    name: "Navigate your homepage",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1601994636372,
    workinstructionId: "2G5bud3gPxP9YF6FP",
  },
  {
    _id: "v7PSDWRkJmMTiBqPB",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5TaSpTDTznYzWrh58",
    type: "workinstruction",
    name: "Update your profile",
    createdBy: "PqKdd7R4EteC3gP2Z",
    createdOn: 1601994773845,
    workinstructionId: "xmvgMKe5X4vTngzJE",
  },
  {
    _id: "uAjfRrCAoKymsZfcP",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "aWd2QttkGSdnDtoQJ",
    type: "workinstruction",
    name: "Video gsm test",
    createdBy: null,
    createdOn: 1602232356999,
    workinstructionId: "yTyfkqTQnfZPMksEr",
  },
  {
    _id: "RWXwaJZoiKDmjpGzz",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "aWd2QttkGSdnDtoQJ",
    type: "workinstruction",
    name: "Video voorbeeld",
    createdBy: null,
    createdOn: 1602232504964,
    workinstructionId: "J3uRt8QCkiAoSLvv7",
  },
  {
    _id: "2RAZTXvd9j9YzvMEZ",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "workinstruction",
    name: "6. Preview work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603270078367,
    workinstructionId: "KdyrD49qJvbZW496j",
  },
  {
    _id: "v7Lm69kAfL5MXBZ3d",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "workinstruction",
    name: "7. Revision History",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603272655763,
    workinstructionId: "eLQRWyeDsCsTvemQX",
  },
  {
    _id: "ig9mWDsBYFAdmzJ6X",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "workinstruction",
    name: "9. Sharing a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603274624814,
    workinstructionId: "fzyGZRKBg5Gg5XP76",
  },
  {
    _id: "h7JaTjjS82ysJwp5x",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "workinstruction",
    name: "8. Create official version",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603280477289,
    workinstructionId: "QztmzfAta2oaS4n7Q",
  },
  {
    _id: "E33TEEFcTvkv3ntNo",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Audits",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603447004055,
    spotId: "qMfcobhPXQfizxsvM",
  },
  {
    _id: "c8DGGSFnJXr9y6YY9",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "E33TEEFcTvkv3ntNo",
    type: "workinstruction",
    name: "Planning",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603447950413,
    workinstructionId: "jvrRcP3bMq2xuuDRh",
  },
  {
    _id: "SRTjQvFneb2kvvFsH",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "E33TEEFcTvkv3ntNo",
    type: "workinstruction",
    name: "Audits",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603452414648,
    workinstructionId: "PZCSewF2Pgh9rr3oR",
  },
  {
    _id: "xFrJbfnrPwJ4CB3pz",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5EazMooSjuoSEgCgE",
    type: "workinstruction",
    name: "Variants",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603706411280,
    workinstructionId: "9NXjSye5sdtMab6mY",
  },
  {
    _id: "ogncZ3uEJQDJEWueA",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5EazMooSjuoSEgCgE",
    type: "workinstruction",
    name: "Users",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1603727614825,
    workinstructionId: "Me5gBKNJAsMP8vF8t",
  },
  {
    _id: "KDCud9hFkZksKgJp7",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "5EazMooSjuoSEgCgE",
    type: "zone",
    name: "Device",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604314947427,
    spotId: "2gNNcyDXuPzimfQDf",
  },
  {
    _id: "9GEQA9dYhLH7Hcj3e",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KDCud9hFkZksKgJp7",
    type: "workinstruction",
    name: "Adding devices",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604314988505,
    workinstructionId: "BLPbYimmK3HSJr9MA",
  },
  {
    _id: "WzjkgaRnigMd6Hv6i",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KDCud9hFkZksKgJp7",
    type: "workinstruction",
    name: "Edit devices",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604395665006,
    workinstructionId: "Dh5kxFEKFqwz72BSg",
  },
  {
    _id: "moEcLE4HiHMWokcvx",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KDCud9hFkZksKgJp7",
    type: "workinstruction",
    name: "Configure devices",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604399980922,
    workinstructionId: "vvmjBBbe8pFqbA387",
  },
  {
    _id: "DMJABHc6vtTdN4rz2",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "cxXikphpt9jYZkfR5",
    type: "workinstruction",
    name: "Assign a work instruction related to an article category to a zone",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604414033388,
    workinstructionId: "7eobQ26xcJzD3dLMH",
  },
  {
    _id: "YC3StabQYP6t4wGqb",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "qDkaSArDHChwfzN3Q",
    type: "workinstruction",
    name: "Resources",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604486556676,
    workinstructionId: "b66fdRw5umL8D23Fg",
  },
  {
    _id: "qDkaSArDHChwfzN3Q",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "KDCud9hFkZksKgJp7",
    type: "zone",
    name: "Resource",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604488072031,
    spotId: "hpFabA5NhZKeJ3yih",
  },
  {
    _id: "PaMMhaQ8rbRe3umip",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "qDkaSArDHChwfzN3Q",
    type: "workinstruction",
    name: "Symbols",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604501751719,
    workinstructionId: "6Q6NFsxSuJM7yr32F",
  },
  {
    _id: "kW8t5NfjEpYh3x7C2",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "iivGuAKQnbEtaG2qH",
    type: "zone",
    name: "Operator interface",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604587286126,
    spotId: "Ni2ygq8vvfjYe9JXY",
  },
  {
    _id: "5ey3TbHR8sty5GCzA",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "kW8t5NfjEpYh3x7C2",
    type: "workinstruction",
    name: "Inleiding tot operator interface",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604588897851,
    workinstructionId: "kDo9BuTr4TChTfwef",
  },
  {
    _id: "NpNnvLGeQ6aHfMekL",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "kW8t5NfjEpYh3x7C2",
    type: "workinstruction",
    name: "Homepage",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604651995809,
    workinstructionId: "L7wB7zLXYeQtnCpS8",
  },
  {
    _id: "KQaLPx75ZBZgq92Bb",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "zone",
    name: "First versions (Mitchell)",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604914596073,
    spotId: "nS3AbSXQhWAQPFTfQ",
  },
  {
    _id: "ph4MyctncduSicTGq",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "zone",
    name: "1. Create work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604916415150,
    spotId: "uQccZgLzyonHPTjfR",
  },
  {
    _id: "orCDhXtzmFwBW479D",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "ph4MyctncduSicTGq",
    type: "workinstruction",
    name: "How to create a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604916443869,
    workinstructionId: "S3j3qCq9R49kzuEXv",
  },
  {
    _id: "E6zP9do6RkfHXiich",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "ph4MyctncduSicTGq",
    type: "workinstruction",
    name: "How to add instruction steps to a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604916517641,
    workinstructionId: "9MA3xK8tsLyFGmb4B",
  },
  {
    _id: "HmyBufLHukTtfZsmX",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "ph4MyctncduSicTGq",
    type: "workinstruction",
    name: "How to add an instruction block",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604916723075,
    workinstructionId: "pfTdy2jBjFLH8sFCq",
  },
  {
    _id: "Lkq9iivJySFAf2ksv",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "zone",
    name: "2. Edit work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604917061000,
    spotId: "eJAzqYcRBBSEKaZFo",
  },
  {
    _id: "CuRMgPqEgLJ9oWxsX",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Lkq9iivJySFAf2ksv",
    type: "workinstruction",
    name: "How to edit a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604917101599,
    workinstructionId: "5wFEduAkekcxzTGCR",
  },
  {
    _id: "YbZnFFsDBLSMxdXGn",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Lkq9iivJySFAf2ksv",
    type: "workinstruction",
    name: "How to edit an instruction step",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604917140696,
    workinstructionId: "263Q3sYoAzutwevpW",
  },
  {
    _id: "XbPn6MMAxkx8YNZhF",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Lkq9iivJySFAf2ksv",
    type: "workinstruction",
    name: "How to edit an instruction block",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604917200578,
    workinstructionId: "XD6j9jTdYRbxJ4KrX",
  },
  {
    _id: "JAE5zzWwRQSeAWSLj",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "zone",
    name: "3. Instruction step editor",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604917808988,
    spotId: "djooqSCpGC6oSNtsj",
  },
  {
    _id: "y32onQqHMJq373Ej5",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "JAE5zzWwRQSeAWSLj",
    type: "workinstruction",
    name: "Navigate through the work instruction editor",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604917830116,
    workinstructionId: "cKkiin95Kqm4fyEMH",
  },
  {
    _id: "MisMN2JE7ZsaPeZnq",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "JAE5zzWwRQSeAWSLj",
    type: "zone",
    name: "Instruction step editor-tabs",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604918264954,
    spotId: "miGdm6Pwr5KcJT3TK",
  },
  {
    _id: "DtCuJ4T3WLjeHQSDr",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "MisMN2JE7ZsaPeZnq",
    type: "workinstruction",
    name: "General",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604918310299,
    workinstructionId: "ZuZ5Gh85YaKwEGfhQ",
  },
  {
    _id: "dvsfHFY7r3geijpjf",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "MisMN2JE7ZsaPeZnq",
    type: "workinstruction",
    name: "Time Study",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604918445402,
    workinstructionId: "PG952Ey8RrBMnspqJ",
  },
  {
    _id: "QXBXrkTtX6NeouLLK",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "MisMN2JE7ZsaPeZnq",
    type: "workinstruction",
    name: "Equipment & Symbols",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604918618717,
    workinstructionId: "xDkkdguG4D4ECaSuF",
  },
  {
    _id: "CggKYdZQRF5Fcfdzj",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "MisMN2JE7ZsaPeZnq",
    type: "zone",
    name: "Visuals",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604918679844,
    spotId: "JZTQzXSQAWMAQ7Cxu",
  },
  {
    _id: "w3YFgN23vAcoNLdHh",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "CggKYdZQRF5Fcfdzj",
    type: "workinstruction",
    name: "How to add images to an instruction step",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604918719343,
    workinstructionId: "E2jCFmoLvuNwb3QEb",
  },
  {
    _id: "2FxaciPEciDFGZAh4",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "CggKYdZQRF5Fcfdzj",
    type: "workinstruction",
    name: "How to add visuals to images",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604919152671,
    workinstructionId: "4XLuY5q9dvB25irYH",
  },
  {
    _id: "amoY6wHPL86BoGLWt",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "CggKYdZQRF5Fcfdzj",
    type: "workinstruction",
    name: "How to edit visuals",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604919190441,
    workinstructionId: "BwyRsadTQeGCiyFb4",
  },
  {
    _id: "JxeT3aFGvBoFMyayN",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "MisMN2JE7ZsaPeZnq",
    type: "workinstruction",
    name: "Revision history",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604919213067,
    workinstructionId: "WjA8YXiX9pbP9TGeE",
  },
  {
    _id: "KdvDgojHdMFk984Su",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "MisMN2JE7ZsaPeZnq",
    type: "workinstruction",
    name: "Checks",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604919366083,
    workinstructionId: "uQGtnCNKAH5LhivSS",
  },
  {
    _id: "g9n5SmrmZmgbTftQv",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "zone",
    name: "4. Adding checks to a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604919832385,
    spotId: "KhrKJGBtpYkrKoDRi",
  },
  {
    _id: "ktXzpChWXRJ6XJ2Pg",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "g9n5SmrmZmgbTftQv",
    type: "workinstruction",
    name: "How to add checks to a workinstruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604919842075,
    workinstructionId: "ouogZaMjzD9WRAAq9",
  },
  {
    _id: "Mp2etv2orzvKmc6xr",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "GeAQ4ssegbS36D2Pg",
    type: "zone",
    name: "5. Adding variants to a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604920001342,
    spotId: "ZEgwJK74LpoukkEmG",
  },
  {
    _id: "hywFDbiurnSd8R3He",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Mp2etv2orzvKmc6xr",
    type: "workinstruction",
    name: "What is a variant",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604920056980,
    workinstructionId: "g3cSkNRTDfgtSHNQx",
  },
  {
    _id: "exdtZL4dn5raCF4Gc",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Mp2etv2orzvKmc6xr",
    type: "workinstruction",
    name: "How to add a variant to a work instruction",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604920074956,
    workinstructionId: "FMMyRx4dc7GEpL7kc",
  },
  {
    _id: "gskPQSartdkHWZktE",
    companyId: "JkwkmxFtvPfoXqyjf",
    parent: "Mp2etv2orzvKmc6xr",
    type: "workinstruction",
    name: "How to edit a variant",
    createdBy: "LPj8tEruTywkM3EGP",
    createdOn: 1604920092711,
    workinstructionId: "JYERr8jXcpXGg4iv2",
  },
];
